<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <url>https://github.com/celements/celements-RTE-langs</url>
  <parent>
    <groupId>com.celements</groupId>
    <artifactId>celements-parent</artifactId>
    <version>7.2-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>tinymce-langs-v4</artifactId>
  <version>7.2-SNAPSHOT</version>
  <packaging>war</packaging>
  <name>TinyMCE Language Files</name>
  <licenses>
    <license>
      <name>LGPL 2.1</name>
      <url>http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <scm>
    <connection>scm:git:git://github.com/celements/celements-RTE-langs</connection>
    <developerConnection>scm:git:git@github.com:celements/celements-RTE-langs.git</developerConnection>
    <url>https://github.com/celements/celements-RTE-langs</url>
    <tag>HEAD</tag>
  </scm>
  <dependencies>
    <!-- Add here all your dependencies -->
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>tinymce-base-v4</artifactId>
      <type>war</type>
    </dependency>
  </dependencies>
  <build>
    <finalName>tinymce-langs-v4</finalName>
  </build>
</project>
